Documentation updated (READMES and folders). Closes #2
Hernancano98/Project-Book pull request #3
Opened 2020-07-29 20:50 UTC by Hernancano98

## **Description:** 

The improvements suggested in **issue #2** by @totigm are done in this PR, with some additions that @Enzito-dev and @Hernancano98 , propose. In addition to what is proposed in the **issue #2**, we made some updates in the README.md files like descriptions and more subdirectories that keep the order and organization. Each folder has its own README file except the ones that are used to **store images**, that are used in the descriptions, or external files. 

### **Changes made:**

+ **README.md** (main) modified: We add a section for _projects_ and more information.
+ **Python** folder created:
  + **README.md** created
+ **Csharp** folder created:
  + **README.md** created
+ **Java** folder:
  + **README.md** modified
  + **docs** folder created:
     + **img** folder created: contains the images used in READMEs description.
     + **Diagrams.EAP** added: This is a file, made with _Enterprise Architect_, that contains the graphic structure of some projects.
  + **EnzoAvena** folder created:
     + **README.md** created
  + **HernanCano** folder created:
     + **README.md** created
     + **API_REST** folder created:
        + **README.md** created
     + **Examples** folder created:
        + **README.md** created
+ **JavaScript** folder:
  + **README.md** modified
  + **MaximilianoBustos** folder created:
     + **README.md** created
  + **GonzaloMuñoz** folder created:
     + **README.md** created

### **More information:**

Here is the folder's tree and the main README:

![fgyh](https://user-images.githubusercontent.com/68404335/88850965-78df9280-d1c2-11ea-9fd1-6fb588e336c5.png)

And this is the Java folder's README. We suggest that every README be described in this way:

![image](https://user-images.githubusercontent.com/68404335/88851051-97de2480-d1c2-11ea-8f50-fe962a1e765e.png)

Co-Authored-By: Enzo Avena

2020-07-29 23:49 UTC, totigm requested changes
I think that in each language README you shouldn't have links to projects and to collaborators, you should only have one of them, it comes way too repetitive, you already have languages, projects and collaborators in the main README, also, don't put the project's owner name next to the project one.

I suggest that you add a link to the project, and inside the project you have a link to the collaborator's README, where you can find a brief description of who the collaborator is, and a list of his projects, obviously including a link to the corresponding README.

And please, turn your CapsLock off.

2020-07-29 23:49 UTC, totigm commented on Java/README.md
> +The **main objective** with this language is to create software that has a desktop version and a mobile app version, and both versions communicate with the same database. The following diagram shows
I'm not sure if that's the main objective of Java, but in case that you're right, mobile and desktop apps communicate with a backend server (Java main purpose), which communicates with a database, front-end does **not** communicate directly to a database.

```suggestion
The **main objective** with this language is to create software that has a desktop and a mobile app, and both communicate with the same backend. The following diagram shows the idea that motivates the learning of this language:
```

2020-07-29 23:49 UTC, totigm commented on Java/README.md
> ++ [REST API](./HernanCano/API_REST/README.md) - Hernán Cano
Decide if you are going to call it REST API or API REST, you shouldn't call the link REST API and the directory API_REST

```suggestion
+ [REST API](./HernanCano/API_REST/README.md)
```

2020-07-29 23:49 UTC, totigm commented on Java/README.md
> +[<-- BACK TO ROOT](../README.md)
```suggestion
[<-- Back to root](../README.md)
```

2020-07-29 23:49 UTC, totigm commented on Java/README.md
> +Right now we are in the learning and practice stage, but the goal is on track.
What is the goal???

2020-07-29 23:49 UTC, totigm commented on Java/HernanCano/README.md
> +[<-- BACK](../README.md)
```suggestion
[<-- Back](../README.md)
```

2020-07-29 23:49 UTC, totigm commented on Java/HernanCano/Examples/README.md
> +[<-- BACK](../README.md)
```suggestion
[<-- Back](../README.md)
```

2020-07-29 23:49 UTC, totigm commented on Java/HernanCano/API_REST/README.md
> +[<-- BACK TO ROOT](../../../README.md)
```suggestion
[<-- Back to root](../../../README.md)
```

2020-07-29 23:49 UTC, totigm commented on Java/EnzoAvena/README.md
> +[<-- BACK](../README.md)
```suggestion
[<-- Back](../README.md)
```

2020-07-29 23:49 UTC, totigm commented on Csharp/README.md
> +[<-- BACK TO ROOT](../README.md)
```suggestion
[<-- Back to root](../README.md)
```

2020-07-29 23:49 UTC, totigm commented on Csharp/README.md
> +
Add a brief description of the language

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on README.md
> +  - [REST API](./Java/HernanCano/API_REST/README.md) - Hernán Cano
Decide if you are going to call it REST API or API REST, you shouldn't call the link REST API and the directory API_REST

```suggestion
  - [REST API](./Java/HernanCano/API_REST/README.md)
```

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on README.md
> +  - [C#](./Csharp/README.md)
Please, change the name of the directory to C#

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on Java/EnzoAvena/README.md
> +# **Enzo Avena**
```suggestion
# **[Avena Enzo](https://github.com/Enzito-dev)**
```

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on Java/HernanCano/API_REST/README.md
> +[<-- BACK](../README.md)
```suggestion
[<-- Back](../README.md)
```

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on Java/HernanCano/README.md
> +    - [REST API](./API_REST/README.md)
Decide if you are going to call it REST API or API REST, you shouldn't call the link REST API and the directory API_REST

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on Java/README.md
> +[<-- BACK TO ROOT](../README.md)
```suggestion
[<-- Back to root](../README.md)
```

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on Java/HernanCano/API_REST/README.md
> +![RestApi](../../docs/img/RestApi.png)
Decide if you are going to call it REST API or API REST, you shouldn't call the link and the image REST API and the directory API_REST

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on JavaScript/GonzaloMuñoz/README.md
> +[<-- BACK](../README.md)
```suggestion
[<-- Back](../README.md)
```

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on JavaScript/MaximilianoBustos/README.md
> +[<-- BACK](../README.md)
```suggestion
[<-- Back](../README.md)
```

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on JavaScript/README.md
> +[<-- BACK TO ROOT](../README.md)
```suggestion
[<-- Back to root](../README.md)
```

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on Python/README.md
> +[<-- BACK TO ROOT](../README.md)
```suggestion
[<-- Back to root](../README.md)
```

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on Java/README.md
> +### Projects:
Why do you go from a # to a ###? your skipping h2
```suggestion
## Projects:
```

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on Java/README.md
> +### Sub-directories:
Why do you go from a # to a ###? your skipping h2
```suggestion
## Sub-directories:
```

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on JavaScript/README.md
> +[<-- BACK TO ROOT](../README.md)
```suggestion
[<-- Back to root](../README.md)
```

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on JavaScript/README.md
> +### Sub-directories:
Why do you go from a # to a ###? your skipping h2
```suggestion
## Sub-directories:
```

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on JavaScript/README.md
If in your Java directory you have

```
# Java
## Projects
## Sub-directories
```

You shouldn't skip ## Projects in JS, even if there aren't any projects yet, you could add something like

```
## Projects
- // To do
```

```suggestion
## Projects
- // To do
```

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on Python/README.md
> +
Add a brief description of the language

2020-07-29 23:49 UTC, gonzalomunozsouthworks commented on README.md
> +This is a collaborative repository about a **collection of projects** that use **different technologies**. Each collaborator uploads his own code in the corresponding folders with a complete descript
```suggestion
This is a collaborative repository about a **collection of projects** that use **different technologies**. Each collaborator uploads his own code to the corresponding directory with a complete description of his work.
```

2020-07-30 00:10 UTC, Hernancano98 commented on Java/README.md
> +Right now we are in the learning and practice stage, but the goal is on track.
The goal is to build something like these:

Create working software that has a desktop version and a mobile app version, and both versions communicate with the same database.

2020-07-30 00:18 UTC, gonzalomunozsouthworks commented on Java/README.md
> +Right now we are in the learning and practice stage, but the goal is on track.
Then I'll make another suggestion

```suggestion
Right now we are in the learning and practice stage, but the goal is to create working software that has a desktop and a mobile version, and both communicate with the same back-end service.
```

2020-07-30 01:02 UTC, Hernancano98 commented on Java/README.md
> +Right now we are in the learning and practice stage, but the goal is on track.
If we put that sentence, we will be rewriting the paragraph above the image, please look at the screenshots i left in the PR description. 

This is the paragraph i'm talking about.

![image](https://user-images.githubusercontent.com/68404335/88868629-12b93680-d1e7-11ea-8310-f100fbb05139.png)

2020-07-30 01:18 UTC, gonzalomunozsouthworks commented on Java/README.md
> +Right now we are in the learning and practice stage, but the goal is on track.
You're right, keep it the way it is.

2020-07-30 13:23 UTC, merged